### ISSUE TITLE
Release latest changes to Maven Central

### ISSUE THREAD

**Issue by ismarslomic** [trevershick/ldap-test-utils#11]
Hi,
could you please release latest version of the code to Maven Central. Currently Maven Central has v2.0.0 which is from 16. Nov 2016. This version is also missing the `useSchema` annotation, which I really need

**Comment by ismarslomic** [comment]
Hi, would you be able to do this release so I can avoid forking this repo just to do it my self in our internal mvn repo?

**Comment by nacho4d** [comment]
This seems to be a good library for testing ldap. I am also looking forward for an update in maven :)

**Comment by trevershick** [comment]
Version 2.0.1 has been released. Sorry for the delay. I don't do Java any more and haven't used this in a long time :)
