### ISSUE TITLE
Possible to bind to user entries?

### ISSUE THREAD

**Issue by s0undt3ch** [trevershick/ldap-test-utils#4]
Is it possible to bind using credentials provided by user entries?

**Comment by trevershick** [comment]
I don't think this works now, but I suppose it could.
Could you provide an example of how you'd like to see this?  It seems easy enough to implement.

**Comment by trevershick** [comment]
Sorry the response was so late, I didn't see this issue open for some reason.

**Comment by trevershick** [comment]
What are you trying to do?
Are you creating users via @LdapEntry annotations and then trying to bind to the server via those users?
How do you identify the users (object class)? Are you using 'userPassword' as the ldap attribute for the user?

**Comment by trevershick** [comment]
I have a change that registers any ldap entries with a 'userPassword' attribute (registers them for login). 

Shown below is the ldap entry with a 'userPassword' set and then below that are the bind credentials.  Is this what you're thinking or are you thinking something else?

```
@LdapConfiguration(
  bindDn = "cn=Directory Manager",
  password = "mypass",
  port = 11111,
  base = @LdapEntry(dn = "dc=myroot", objectclass = { "top", "domain" }),
  entries = {
    @LdapEntry(dn = "cn=tshick,dc=myroot",
      objectclass = {"top", "person"},
      attributes = {
        @LdapAttribute(name = "userPassword", value = "thepassword"),
        @LdapAttribute(name = "sn", value = "Shick"),
        @LdapAttribute(name = "cn", value = "tshick")
      })
  }
)

```

then login with:

```
    LdapTemplate t = new LdapTemplate();
    LdapContextSource s = new LdapContextSource();
    s.setUserDn("cn=tshick,dc=myroot");
    s.setPassword("thepassword");

```

**Comment by trevershick** [comment]
I have added tests which demonstrate that you can bind to the ldap server via any user added to the server, either via annotation or ldif file.

**Comment by s0undt3ch** [comment]
I was able to get binding users to work but forgot about this open issue.
