### ISSUE TITLE
Allow to add schema files

### ISSUE THREAD

**Issue by sylvainlaurent** [trevershick/ldap-test-utils#6]
I need to add ldif files for some custom schema...

**Comment by trevershick** [comment]
I'm sorry, i just noticed this.  I've been busy.  I'll get to it soon.

**Comment by trevershick** [comment]
You can alter the schema via LDIF files.  Specifying LDIF files is in the Readme.  I've added a unit test and sample schema ldif file for clarification.  I hope this works for you.
