### ISSUE TITLE
Attribute pwdReset

### ISSUE THREAD

**Issue by clairton** [trevershick/ldap-test-utils#7]
Could I use pwdReset attribute to user reset password on next login?

**Comment by trevershick** [comment]
I'm sorry, i just noticed this.  I am unfamiliar with that.  If the UnboundID server supports it then it should work. I'll look into it.

**Comment by clairton** [comment]
Thank's @trevershick

**Comment by trevershick** [comment]
I'm not sure what you're trying to do here. It looks like this is something not really supported by the unboundid server.  Are wanting the test utils to 'mock out' this sort of behavior?

**Comment by trevershick** [comment]
no more info. closing...
